name: grabbing streams

on:
  schedule:
    - cron: '0 */4 * * *'
  
  
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

       
      - name: config
        run: |
          git config --global user.email "<>"
          git config --global user.name "Update"
      
      
      - name: grab m3u files
        run: |
            pwd
            cd ./core/platforms/
           
            python3 twitch.py astratv2021 > ../../streamss/Astra_TV.m3u8
           
            python3 twitch.py diontv2024 > ../../streamss/DionTvKentrikisMakedonias.m3u8
            
            python3 twitch.py eurotvgreece > ../../streamss/EuroTV.m3u8
            python3 twitch.py orestidatv > ../../streamss/FlashTV.m3u8
            python3 twitch.py kostv2024 > ../../streamss/kostv2024
            python3 twitch.py lepantotv > ../../streams/LePanto.m3u8
            python3 twitch.py pronewstvgr > ../../streamss/ProNews.m3u8
            python3 twitch.py tvkosmosgr > ../../streamss/tvkosmosgr.m3u8
            
            python3 twitch.py topchannelkozani > ../../streamss/Top_Channel_Greece.m3u8
            python3 twitch.py centertv > ../../streamss/centertv.m3u8
            python3 twitch.py livethess2020 > ../../streamss/thessaliatv.m3u8
           
            python3 twitch.py tvstarfm > ../../streamss/tvstarfm.m3u8
            python3 twitch.py extacy_tv > ../../streamss/Extacy_tv.m3u8
            python3 twitch.py alithiavideo > ../../streamss/Alithiavideo.m3u8
        
          
            python3 twitch.py xtvision > ../../streamss/XTV.m3u8
            python3 twitch.py diabatatv > ../../streamss/Diavata_TV.m3u8
            python3 twitch.py iviewtvgr > ../../streamss/iViewTvGr.m3u8
            python3 twitch.py dtpylias > ../../streamss/DTP.m3u8
            python3 twitch.py marontvgr > ../../streamss/marontvgr.m3u8
            python3 twitch.py orthodoxiaradio > ../../streamss/Orthodoxia_Radio_TV.m3u8
            
           
      - name: git add
        run: |
          git add -A
          ls -la 
          
      - name: commit & push
        run: |
          git commit -m "streams updated"
          git push
